services:
  - type: web
    name: spoken-english-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn spoken_english_api.main:app
    workingDir: spoken_english_application
    envVars:
      - key: PYTHONPATH
        value: spoken_english_application
