services:
  - type: web
    name: spoken-english-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    workingDir: spoken_english_api
    envVars:
      - key: PYTHONPATH
        value: .
