name: spoken_english_flutter
description: A Flutter app to practice spoken English
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/