name: spoken_english_flutter
description: A Flutter app to practice spoken English
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  shared_preferences: ^2.2.2   # 👈 ADD THIS LINE

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
